// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// add_to_row
void add_to_row(IntegerMatrix x, int row, int y);
RcppExport SEXP _ppmcmc_add_to_row(SEXP xSEXP, SEXP rowSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type row(rowSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    add_to_row(x, row, y);
    return R_NilValue;
END_RCPP
}
// add_to_col
void add_to_col(IntegerMatrix x, int col, int y);
RcppExport SEXP _ppmcmc_add_to_col(SEXP xSEXP, SEXP colSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type col(colSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    add_to_col(x, col, y);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ppmcmc_add_to_row", (DL_FUNC) &_ppmcmc_add_to_row, 3},
    {"_ppmcmc_add_to_col", (DL_FUNC) &_ppmcmc_add_to_col, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ppmcmc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
