# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Pass matrix by reference and edit the first row.
#' @param x Integer matrix
#' @param row Index of row to modify
#' @param y value to add
#' @export
add_to_row <- function(x, row, y) {
    invisible(.Call(`_ppmcmc_add_to_row`, x, row, y))
}

#' Pass matrix by reference and edit the first column.
#' @param x Integer matrix
#' @param col Index of col to modify
#' @param y value to add
#' @export
add_to_col <- function(x, col, y) {
    invisible(.Call(`_ppmcmc_add_to_col`, x, col, y))
}

